# Generated by Django 4.2.7 on 2024-01-03 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=1000)),
                ("due_date", models.DateField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                ("completed", models.BooleanField()),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("photos", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Photoes",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image1", models.ImageField(blank=True, null=True, upload_to="")),
                ("image2", models.ImageField(blank=True, null=True, upload_to="")),
                ("image3", models.ImageField(blank=True, null=True, upload_to="")),
                ("image4", models.ImageField(blank=True, null=True, upload_to="")),
                ("image5", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "tid",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="tasks.task"
                    ),
                ),
            ],
        ),
    ]
