# Generated by Django 4.2.7 on 2024-01-03 17:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="photoes",
            old_name="image1",
            new_name="image",
        ),
        migrations.RemoveField(
            model_name="photoes",
            name="image2",
        ),
        migrations.RemoveField(
            model_name="photoes",
            name="image3",
        ),
        migrations.RemoveField(
            model_name="photoes",
            name="image4",
        ),
        migrations.RemoveField(
            model_name="photoes",
            name="image5",
        ),
    ]
