# Generated by Django 4.2.7 on 2024-01-03 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_rename_image1_photoes_image_remove_photoes_image2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photoes",
            name="tid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tasks.task"
            ),
        ),
    ]
