# Generated by Django 4.2.7 on 2024-01-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_alter_photoes_tid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="photos",
            new_name="photo1",
        ),
        migrations.AddField(
            model_name="task",
            name="photo2",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="task",
            name="photo3",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.DeleteModel(
            name="Photoes",
        ),
    ]
